In [1]:
import pandas as pd

# Pandas is a in built library of Python, used for Data Manipulation.

In [2]:
df = pd.read_csv("../dataset/student_data.csv")

# Loading of Dataset stored in the following path "C:\Users\ashok\OneDrive\Desktop\EDP Internship\Week - 1\dataset/student_data.csv".
# df - DataFrame, It is the primary data structure in Pandas.

In [3]:
df.head() 

# shows the first 5 records of the dataset.

,Student_ID,Name,Gender,Attendance,Study_Hours,Assignment_Score,Final_Score
0,101,AASHRITHA TIRUMALASETTY,Female,92,3.5,85.0,88
1,102,MYNENI AASRITHA SREE SAI,Female,85,2.5,78.0,80
2,103,VADJE ADITI,Female,90,4.0,82.0,84
3,104,YAMSANI AKSHITH,Male,88,NaN,90.0,91
4,105,SINGIREDDY ANIKETH REDDY,Male,75,2.0,70.0,72

In [4]:
df.tail()

# Displays the last 5 records of the dataset (student_data.csv).

,Student_ID,Name,Gender,Attendance,Study_Hours,Assignment_Score,Final_Score
11,112,KOPPISETTY HARINI,Female,94,4.8,93.0,95
12,113,BALIJAGUDEM HARSHAVARDHAN,Male,87,3.7,84.0,86
13,114,VAKKALAGADDA HIMA VENKATA SATYA PRASAD,Male,90,4.1,88.0,90
14,115,RAGHULAPALLY IKSHITA,Female,82,2.8,77.0,79
15,115,RAGHULAPALLY IKSHITA,Female,82,2.8,77.0,79

In [5]:
df.shape

# It displays the number of rows and columns that are present in the dataset.

(16, 7)

In [6]:
df.columns

# It will display all the column names present in the dataset.

Index(['Student_ID', 'Name', 'Gender', 'Attendance', 'Study_Hours',
       'Assignment_Score', 'Final_Score'],
      dtype='str')

In [7]:
df.dtypes

# It displays the data types of the columns present in the dataset.

Student_ID            int64
Name                    str
Gender                  str
Attendance            int64
Study_Hours         float64
Assignment_Score    float64
Final_Score           int64
dtype: object

In [8]:
df.info()

# It gives the complete information about the Dataset.

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student_ID        16 non-null     int64
 1   Name              16 non-null     str
 2   Gender            16 non-null     str
 3   Attendance        16 non-null     int64
 4   Study_Hours       15 non-null     float64
 5   Assignment_Score  15 non-null     float64
 6   Final_Score       16 non-null     int64
dtypes: float64(2), int64(3), str(2)
memory usage: 1.0 KB

In [9]:
df.describe()

# This gives the statistical summary of the numerical columns.

       Student_ID  Attendance  Study_Hours  Assignment_Score  Final_Score
count   16.000000    16.00000    15.000000         15.000000    16.000000
mean   108.437500    86.31250     3.480000         83.333333    84.500000
std      4.661455     5.85057     0.896182          7.296444     7.580677
min    101.000000    75.00000     2.000000         70.000000    72.000000
25%    104.750000    82.00000     2.800000         77.500000    79.000000
50%    108.500000    87.50000     3.500000         84.000000    85.000000
75%    112.250000    90.25000     4.050000         88.500000    90.000000
max    115.000000    95.00000     5.000000         96.000000    98.000000

In [10]:
df.isnull()

# Checks every cell in the dataset and return True if a cell is empty or return False.

,Student_ID,Name,Gender,Attendance,Study_Hours,Assignment_Score,Final_Score
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False
8,False,False,False,False,False,True,False
9,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False

In [11]:
df.isnull().sum()

# Returns the number of missing values in the dataset in each column.

Student_ID          0
Name                0
Gender              0
Attendance          0
Study_Hours         1
Assignment_Score    1
Final_Score         0
dtype: int64

In [12]:
# Fiiling the missing values in the dataset using the mean values of their respective columns, instead of filling with random values.

df["Study_Hours"] = df["Study_Hours"].fillna(df["Study_Hours"].mean())
df["Assignment_Score"] = df["Assignment_Score"].fillna(df["Assignment_Score"].mean())

In [13]:
df.isnull().sum()

# Verification of null values in the dataset.

Student_ID          0
Name                0
Gender              0
Attendance          0
Study_Hours         0
Assignment_Score    0
Final_Score         0
dtype: int64

In [14]:
df.duplicated()

# Checks for the duplicate records in the dataset.

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
dtype: bool

In [15]:
df.duplicated().sum()

# It counts the number of duplicate rows in the dataset.

np.int64(1)

In [16]:
df = df.drop_duplicates()

# This removes the duplicate records from the dataset.

In [17]:
df.duplicated().sum()

# Verification of the removal of the duplicate records from the dataset.

np.int64(0)

In [18]:
df.shape

# Checking the shape of the dataset (Number of rows and columns) after removing duplicate records.

(15, 7)

In [20]:
df

# This shows the entire cleaned dataset, without any empty cells and without any duplicate or repeated records.

,Student_ID,Name,Gender,Attendance,Study_Hours,Assignment_Score,Final_Score
0,101,AASHRITHA TIRUMALASETTY,Female,92,3.50,85.000000,88
1,102,MYNENI AASRITHA SREE SAI,Female,85,2.50,78.000000,80
2,103,VADJE ADITI,Female,90,4.00,82.000000,84
3,104,YAMSANI AKSHITH,Male,88,3.48,90.000000,91
4,105,SINGIREDDY ANIKETH REDDY,Male,75,2.00,70.000000,72
5,106,ANJALI TIWARI,Female,95,5.00,96.000000,98
6,107,ANURADHA KAWLE,Female,80,3.00,75.000000,76
7,108,SHEELAM APURUPACHANDU,Female,91,4.50,89.000000,90
8,109,ALLUMALLA CHARITHA SREE,Female,78,2.50,83.333333,74
9,110,GADILA DEEPAK,Male,89,3.80,87.000000,89
10,111,POTLACHERUVU GOUTHAM,Male,83,3.20,79.000000,81
11,112,KOPPISETTY HARINI,Female,94,4.80,93.000000,95
12,113,BALIJAGUDEM HARSHAVARDHAN,Male,87,3.70,84.000000,86
13,114,VAKKALAGADDA HIMA VENKATA SATYA PRASAD,Male,90,4.10,88.000000,90
14,115,RAGHULAPALLY IKSHITA,Female,82,2.80,77.000000,79

In [22]:
df.to_csv("../cleaned_dataset/cleaned_student_data.csv", index=False)

# This line of code saves the Cleaned Dataset as a .csv file at the declared decision with the given file name and "index=False" prevents the 
# Pandas from writing an extra column to the .csv file.